export const MIN_TRANSLATE_RATE = 1
export const MIN_TRANSLATE_CAPACITY = 1
export const MIN_BATCH_CHARACTERS = 1
export const MIN_BATCH_ITEMS = 1
export const MIN_TRANSLATE_TIMEOUT_MS = 5_000
export const MIN_TRANSLATE_RETRY_DELAY_MS = 100

export const DEFAULT_REQUEST_RATE = 8
export const DEFAULT_REQUEST_CAPACITY = 60
export const DEFAULT_REQUEST_TIMEOUT_MS = 45_000
export const DEFAULT_REQUEST_MAX_RETRIES = 2
export const DEFAULT_REQUEST_BASE_RETRY_DELAY_MS = 1_000
export const MAX_TRANSLATE_RETRIES = 5

export const DEFAULT_MAX_CHARACTER_PER_BATCH = 1000
export const DEFAULT_MAX_ITEMS_PER_BATCH = 4

export const DEFAULT_BATCH_CONFIG = {
  maxCharactersPerBatch: DEFAULT_MAX_CHARACTER_PER_BATCH,
  maxItemsPerBatch: DEFAULT_MAX_ITEMS_PER_BATCH,
}

export const DEFAULT_AUTO_TRANSLATE_SHORTCUT_KEY = ['alt', 'e']
